name: sentiment_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - openjdk=11.0.21
  - pip
  - pip:
      - pyspark==3.5.1
      - kafka-python==2.0.2
      - pymongo==3.12.1
      - vaderSentiment
      - django==5.0.6
      - pandas==2.2.2
      - matplotlib==3.8.3
      - seaborn==0.13.2
      - nltk==3.8.1
      - jupyter
